server.port=8090
spring.application.name=mindcare-diary-batch

spring.main.allow-bean-definition-overriding=true

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=MINDCARE
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

spring.batch.job.enabled=false