CREATE OR REPLACE FUNCTION MINDCARE.VERIFICA_PRESCRICOES_VENCENDO
    RETURN SYS_REFCURSOR
    IS
    V_PRESCRICOES SYS_REFCURSOR;
BEGIN

    OPEN V_PRESCRICOES FOR

        SELECT
            P.ID,
            P.NUMERO,
            P.ISSUE_DATE,
            P.EXPIRATION_DATE,

            TRUNC(P.EXPIRATION_DATE) - TRUNC(SYSDATE)
                AS DAYS_REMAINING,

            P.CONTROLLED,
            P.VALID,

            P.PACIENTE_ID,

            PACIENTE.NOME_USUARIO
                AS PACIENTE_NOME_USUARIO,

            PACIENTE.NOME_COMPLETO
                AS PACIENTE_NOME_COMPLETO,

            PACIENTE.TOKEN
                AS PACIENTE_TOKEN,

            P.PROFISSIONAL_ID,

            PROFISSIONAL.NOME_USUARIO
                AS PROFISSIONAL_NOME_USUARIO,

            PROFISSIONAL.NOME_COMPLETO
                AS PROFISSIONAL_NOME_COMPLETO

        FROM MINDCARE.PRESCRIPTION P

                 INNER JOIN MINDCARE.USUARIO PACIENTE
                            ON PACIENTE.ID = P.PACIENTE_ID

                 INNER JOIN MINDCARE.USUARIO PROFISSIONAL
                            ON PROFISSIONAL.ID = P.PROFISSIONAL_ID

        WHERE P.VALID = 1

          AND TRUNC(P.EXPIRATION_DATE)
            BETWEEN TRUNC(SYSDATE)
            AND TRUNC(SYSDATE) + 7

        ORDER BY P.EXPIRATION_DATE ASC;

    RETURN V_PRESCRICOES;

END;
/
/